// Source-backed records checked against MaisonLooks on 2026-09-03.
// The downloaded images are source-listing images, not buyer-uploaded QC photos.
window.JOYA_PRODUCTS = [
  {
    id: "clean-low-sneaker",
    name: "Nike Air Force 1 White Rope Laces Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks",
    sourceUrl: "https://maisonlooks.com/en/p/nike-air-force-1-white-rope-laces-sneakers-3d7485",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775462939577-561746983.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 252,
    sizes: ["36", "36.5", "37.5", "38", "38.5", "39", "40", "40.5", "41", "42", "42.5", "43", "44", "44.5", "45", "46"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/nike-air-force-1-rope.webp",
    tags: ["low top", "leather", "white"]
  },
  {
    id: "retro-runner-shoe",
    name: "Asics Gel-NYC White/Green Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks",
    sourceUrl: "https://maisonlooks.com/en/p/asics-gel-nyc-silver-green-sneakers-2e2807",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775466531961-250413849.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 400,
    sizes: ["36", "37", "37.5", "38", "39", "39.5", "40", "40.5", "41.5", "42", "42.5", "43.5", "44", "45"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/asics-gel-nyc.webp",
    tags: ["runner", "mesh", "silver green"]
  },
  {
    id: "court-training-sneaker",
    name: "Adidas Samba White/Black Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks",
    sourceUrl: "https://maisonlooks.com/en/p/adidas-samba-white-black-sneakers-07f84b",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775307544568-394485322.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 236,
    sizes: ["36", "36.5", "37", "38", "38.5", "39", "40", "40.5", "41", "42", "42.5", "43", "44", "44.5", "45"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/adidas-samba.webp",
    tags: ["court", "leather", "gum sole"]
  },
  {
    id: "gallery-graphic-tee",
    name: "Amiri Black Leopard Print T-Shirt",
    category: "T-Shirts",
    evidenceStatus: "source-checked",
    sourceName: "Street Style by MaisonLooks",
    sourceUrl: "https://streetstyle.maisonlooks.com/en/p/amiri-black-leopard-print-t-shirt-a4f10e",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1778681915556-320676783.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 88,
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/amiri-leopard-tee.webp",
    tags: ["graphic", "cotton", "relaxed"]
  },
  {
    id: "tech-audio-headphones",
    name: "Apple AirPods Max (Plastic) Black Headphones",
    category: "Tech",
    evidenceStatus: "source-checked",
    sourceName: "Street Style by MaisonLooks",
    sourceUrl: "https://streetstyle.maisonlooks.com/en/p/apple-airpods-max-plastic-black-headphones-32047b",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1778312334863-514077315.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 490,
    sizes: ["One size"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/apple-airpods-max.webp",
    tags: ["audio", "black", "synthetic"]
  },
  {
    id: "white-logo-cap",
    name: "Prada White Logo Cap Headwear",
    category: "Accessories",
    evidenceStatus: "source-checked",
    sourceName: "Street Style by MaisonLooks",
    sourceUrl: "https://streetstyle.maisonlooks.com/zh/p/prada-white-logo-cap-headwear-3f0755",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1778413398515-861900396.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 95,
    sizes: ["One size", "Exact measurements not displayed"],
    stock: "476 shown; source said checked about 8 days earlier",
    image: "/assets/qc/prada-white-cap.webp",
    tags: ["cap", "white", "logo"]
  },
  {
    id: "air-jordan-4-black-white",
    name: "Nike Air Jordan 4 Black/White Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/air-jordan-4-retro-black-white-sneakers-b9eb20",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775457353087-395226294.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 300,
    sizes: ["40", "40.5", "41", "42", "42.5", "43", "44", "44.5", "45", "46", "47.5", "48.5"],
    stock: "39,861 shown across all sizes; source said checked about 1 day earlier",
    image: "/assets/qc/air-jordan-4-black-white.webp",
    tags: ["high top", "black white", "basketball"]
  },
  {
    id: "gel-kayano-white-black",
    name: "ASICS Gel-Kayano 26 White/Black Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/asics-gel-kayano-26-white-black-running-sneakers-c34676",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775553311788-263960732.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 333.6,
    sizes: ["EU36", "EU37", "EU37.5", "EU38", "EU39", "EU39.5", "EU40", "EU40.5", "EU41.5", "EU42", "EU42.5", "EU43.5", "EU44", "EU44.5", "EU45"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/asics-gel-kayano.webp",
    tags: ["runner", "white black", "cushioned"]
  },
  {
    id: "margiela-replica-beige",
    name: "Maison Margiela Replica Beige Low Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/maison-margiela-replica-beige-low-sneakers-cc34fd",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775742601529-166357521.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 420,
    sizes: ["EU35", "EU36", "EU37", "EU38", "EU39", "EU40", "EU41", "EU42", "EU43", "EU44", "EU45"],
    stock: "1,848 shown across all sizes; source said checked about 1 day earlier",
    image: "/assets/qc/maison-margiela-replica-beige.webp",
    tags: ["low top", "beige", "retro"]
  },
  {
    id: "lv-trainer-white-blue",
    name: "Louis Vuitton LV Trainer White/Blue Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/louis-vuitton-lv-trainer-sneakers-in-white-and-navy-4e3654",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775469889350-396512629.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 505.92,
    sizes: ["EU36", "EU37", "EU38", "EU39", "EU40", "EU41", "EU42", "EU43", "EU44", "EU45", "EU46"],
    stock: "1,078 shown in stock; source said checked on the inspection day",
    image: "/assets/qc/lv-trainer-blue-white.webp",
    tags: ["trainer", "white blue", "leather"]
  },
  {
    id: "arrow-sneaker-black-yellow",
    name: "Unisex Black & Yellow Arrow Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/black-and-yellow-off-white-sneakers-57a333",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775523410997-764797434.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 336,
    sizes: ["EU36", "EU37", "EU38", "EU39", "EU40", "EU41", "EU42", "EU43", "EU44", "EU45"],
    stock: "9,900 shown in stock; source said checked on the inspection day",
    image: "/assets/qc/off-white-arrow-black-yellow.webp",
    tags: ["low top", "black yellow", "arrow"]
  },
  {
    id: "mm6-blakey-black-white",
    name: "MM6 Blakey Black & White Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/mmy-blakey-black-and-white-canvas-sneakers-8d94d4",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775222194831-603183757.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 321.6,
    sizes: ["EU35", "EU36", "EU37", "EU38", "EU39", "EU40", "EU41", "EU42", "EU43", "EU44", "EU45"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/mm6-blakey-black-white.webp",
    tags: ["canvas", "black white", "low top"]
  },
  {
    id: "pegasus-black-orange",
    name: "Nike Air Zoom Pegasus Black/Orange Sneakers",
    category: "Sneakers",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/nike-air-zoom-pegasus-black-orange-sneakers-c2aca4",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1776957627203-365740352.webp",
    checkedAt: "2026-09-03",
    qcStatus: "not-published",
    qcLabel: "Buyer QC not published",
    buyerPhotoCount: null,
    sourcePageVerified: true,
    priceCny: 250,
    sizes: ["36", "37", "38", "38.5", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48.5"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/nike-pegasus-black-orange.webp",
    tags: ["runner", "black orange", "air zoom"]
  },
  {
    id: "erd-black-tee",
    name: "Enfants Riches Déprimés 'ERD' Black T-Shirt",
    category: "T-Shirts",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/enfants-riches-d-prim-s-black-graphic-t-shirt-25f9e6",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775529922258-732236573.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 94.8,
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: "4,995 shown across all sizes; source said checked about 3 days earlier",
    image: "/assets/qc/erd-black-tee.webp",
    tags: ["cotton", "oversized", "graphic"]
  },
  {
    id: "gallery-art-that-kills-tee",
    name: "Gallery Dept. Art That Kills Black T-Shirt",
    category: "T-Shirts",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/gallery-dept-black-oversized-t-shirt-9c265c",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775457143775-420262173.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 72,
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: "Not listed on the source page when checked.",
    image: "/assets/qc/gallery-art-that-kills.webp",
    tags: ["cotton", "oversized", "graphic"]
  },
  {
    id: "distressed-denim-jeans",
    name: "Distressed Denim Jeans with Rips and Paint Splatter",
    category: "Pants",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/dsquared2-distressed-denim-jeans-452e6f",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775548244055-302261515.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 285.6,
    sizes: ["28 (44)", "30 (46)", "32 (48)", "34 (50)", "36 (52)", "38 (54)"],
    stock: "1,496 shown in stock; source said checked about 1 day earlier",
    image: "/assets/qc/dsquared-distressed-jeans.webp",
    tags: ["denim", "distressed", "paint splatter"]
  },
  {
    id: "dior-oblique-cardholder",
    name: "Dior Oblique Card Holder Black",
    category: "Accessories",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/dior-oblique-card-holder-in-black-and-white-964c15",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775224255004-108129567.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 43.08,
    sizes: ["One size"],
    stock: "341 shown in stock; source said checked about 1 day earlier",
    image: "/assets/qc/dior-oblique-cardholder.webp",
    tags: ["card holder", "black white", "monogram"]
  },
  {
    id: "corteiz-track-pants",
    name: "Corteiz RTW Black Track Pants with White Piping",
    category: "Pants",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/cavetze-black-track-pants-with-white-side-stripes-fa931d",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775224631949-900033792.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 153.6,
    sizes: ["S", "M", "L", "XL"],
    stock: "3,994 shown across all sizes; source said checked on the inspection day",
    image: "/assets/qc/corteiz-track-pants.webp",
    tags: ["track pants", "relaxed", "black white"]
  },
  {
    id: "supreme-99-long-sleeve",
    name: "Supreme White '99' Long Sleeve T-Shirt",
    category: "T-Shirts",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/supreme-box-logo-long-sleeve-tee-in-white-with-blue-99-8f8a15",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775238861933-863700160.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 265,
    sizes: ["S", "M", "L", "XL"],
    stock: "194 shown in stock; source said checked about 1 day earlier",
    image: "/assets/qc/supreme-99-long-sleeve.webp",
    tags: ["cotton", "long sleeve", "white blue"]
  },
  {
    id: "psg-black-gold-jersey",
    name: "Paris Saint-Germain Qatar Airways Black & Gold Jersey",
    category: "T-Shirts",
    evidenceStatus: "source-checked",
    sourceName: "MaisonLooks official storefront",
    sourceUrl: "https://official.maisonlooks.com/en/p/paris-saint-germain-qatar-airways-black-gold-jersey-f72b63",
    imageSourceUrl: "https://cdn.maisonlooks.com/products/file-1775762832241-120469580.webp",
    checkedAt: "2026-09-03",
    qcStatus: "empty",
    qcLabel: "0 buyer QC photos",
    buyerPhotoCount: 0,
    sourcePageVerified: true,
    priceCny: 90,
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: "500 shown in stock; source said checked about 5 days earlier",
    image: "/assets/qc/psg-black-gold-jersey.webp",
    tags: ["polyester", "jersey", "black gold"]
  }
];
